# test-deploy.yml

name: 部署测试

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Test SSH connection
        #run: ssh -o LogLevel=DEBUG3 -o StrictHostKeyChecking=no root@185.239.227.214
        run: ssh -vvv -o StrictHostKeyChecking=no root@185.239.227.214     

      - name: Deploy to remote server
        working-directory: ./
        run: |
          scp -o StrictHostKeyChecking=no genimi-telebot-1.1.py root@185.239.227.214:/www/
          ssh root@185.239.227.214 "cd /www/"
          echo "测试成功！"
        #scp -o StrictHostKeyChecking=no public.tar.gz root@185.239.227.214:/www/
        
      